### ISSUE TITLE
Update package name in plugin store (?)

### ISSUE THREAD

**Issue by tyssen** [fantasticmachine/existential#3]
I tried to install this via CLI using `composer require moresoda/existential` and got:

> Could not find a matching version of package moresoda/existential. Check th
  e package spelling, your version constraint and that the package is availab
  le in a stability which matches your minimum-stability (stable).

A check of Packagist and I found `davidhellmann/existential` which installed fine.

**Comment by peteeveleigh** [comment]
David made a fork of this to add some features (I think). I'm not sure what's happened with the reference on Packagist.

I've re-added the plugin to Packagist for *this* repository. Would you mind trying to install it again and let me know if it now works for you?

**Comment by tyssen** [comment]
Yep, all good now. 👍
